title:              Matchmalo blog
email:              hello@matchmalo.com
description:        Actionable marketing tips and B2B brand collaboration guides that will help you grow your business at almost no cost.
author:             Ulrich Medenou
baseurl:            ""
url:                "https://blog.matchmalo.com"

# Social Profiles
twitter_username: matchmalo
github_username:    
facebook_username:  groups/b2bpartnershipmarketing 
instagram_username:  low_cost_growth
linkedin_username: company/matchmalo

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           6
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
